# words for hangman game
words = ("apple", "orange", "banana", "coconut", "pineapple", 'electricity', 'donkey',  
        'computer', 'desktop', 'hardware', 'xerox', 'transistor', "dog", 'treasure',
        'engineering', 'hangman', 'circuit', 'imagination', 'robot', 'memory', 'power', 
        'submarine', 'chess', 'resistance', 'matrix', 'function', 'laser', 'mechanism', 
        'bodyguard', 'titanic', 'global', 'ozone', 'bridge', 'technology', 'spider',
        'pyramid', 'sphere', 'member', 'warning', 'yourself', 'screen', 'language',
        'system', 'internet', 'parameter', 'traffic', 'network', 'filter', 'nucleus',
        'automatic', 'microphone', 'cassette', 'operation', 'country', 'beautiful',
        'picture', 'teacher', 'superman', 'undertaker', 'alarm', 'process', 'keyboard', 
        'electron', 'certificate', 'grandfather', 'landmark', 'relativity', 'eraser',
        'design', 'football', 'human', 'musician', 'egyptian', 'elephant', 'queen',
        'message', 'wallpaper', 'nationality', 'answer', 'wrong', 'statement', 'forest',
        'puzzle', 'voltage', 'current', 'mathematics', 'wisdom', 'dream', 'supermarket',
        'database', 'collection', 'barrier', 'project', 'sunlight', 'figure', 'graph',
        'battle', 'hundred', 'signal', 'thousand', 'transformation', 'daughter',
        'communication', 'microwave', 'electronic', 'peace', 'wireless', 'delete',
        'brain', 'control', 'prophet', 'freedom', 'harbour', 'confidence', 'positive',
        'harvest', 'hunger', 'woman', 'children', 'stranger', 'garden', 'pleasure',
        'between', 'recognition', 'tomorrow', 'autumn', 'monkey', 'spring', 'winter',
        'classification', 'typewriter', 'success', 'difference', 'acoustics', 'astronomy',
        'agreement', 'sorrow', 'christmas', 'silver', 'birthday', 'championship', 'friend',
        'comfortable', 'diffusion', 'murder', 'policeman', 'science', 'desert', 'basketball',
        'blood', 'funeral', 'silence', 'garment', 'merchant', 'spirit', 'punishment',
        'measurement', 'ocean', 'digital', 'illusion', 'tyrant', 'castle', 'passion',
        'magician', 'remedy', 'knowledge', 'threshold', 'number', 'vision', 'expectation',
        'absence', 'mystery', 'morning', 'device', 'thoughts', 'spirit', 'future')

